[package]
name = "rust-audio-sandbox"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "0.14"
clap = { version = "4.0", features = ["derive"] }
anyhow = "1.0"
opus = "0.3"
ringbuf = "0.2"